### ISSUE TITLE
Using "UTF-8" as default encoding causes sendmailR to fail

### ISSUE THREAD

**Issue by hannarud** [olafmersmann/sendmailR#2]
The minimum reproducible example:

1. Start a new R session, do the following:
`library(sendmailR)`
`sendmail(from = "<your_email@gmail.com>",
         to = "<your_email@gmail.com>",
         subject = "Test",
         msg = mime_part("Body text"),
         control=list(smtpServer="ASPMX.L.GOOGLE.COM", smtpPort="25"))`
Email will be sent successfully.
2. Set `options(encoding = "UTF-8")` and try to send email from 1 once again. Result: **Error in if (code == lcode) { : argument is of length zero** mistake appears.

My  default language settings are "English_United States.1252".

**Comment by DavorJ** [comment]
Nice find Hanna! Seems to be is a very old (2014) unresolved issue:

http://r.789695.n4.nabble.com/sendmailR-error-if-code-lcode-argument-is-of-length-zero-td4695166.html

My default is "native.enc".

**Comment by ndevln** [comment]
I think this problem is solved since R 4.2, since R now supports and defaults to native UTF-8 on Windows.
