### ISSUE TITLE
next InitializeSecurityContext failed : SEC_E_CERT_EXPIRED (0x80090328)

### ISSUE THREAD

**Issue by pavelaegorov** [olafmersmann/sendmailR#7]
Hi Olaf! Thank you for you work developing this package. 
I encouneterd an issue when implementing package for sending reports. 
I wrote a piece of code that worked perfectly well at 11:00  
The same piece of code end stopped working with the following error today at 13:00:

Error in curl_fetch_memory(smtp_server, handle = h) : 
  schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328)

Could you please help with this.

**Comment by olafmersmann** [comment]
Looks like the certificate of the SMTP server expired. Can you share the name of the server (if it is publicly accessible)?

**Comment by olafmersmann** [comment]
If the issue persists, please reopen.
